#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define IDD_DIALOG1                             101
#define IDR_TOOLBAR1                            102
#define IDI_CLIENT_LIST_ICON1                   111
#define IDI_CLIENT_LIST_ICON2                   112
#define IDI_CLIENT_LIST_ICON3                   113
#define IDI_CLIENT_LIST_ICON4                   114
#define IDI_CLIENT_LIST_ICON5                   115
#define IDI_CLIENT_LIST_ICON6                   116
#define IDI_FILE_DOWN                           117
#define IDI_FILE_UP                             118
#define IDI_DISK                                119
#define IDI_CDROM                               120
#define IDI_UNKNOWN                             121
#define IDR_TOOLBAR2                            130
#define IDR_MENU2                               131
#define IDR_MENU3                               132
#define IDD_DIALOG_MAKE_FILE                    134
#define IDD_DIALOG_CENTER_CONFIG                136
#define IDD_DIALOG_DDOS                         138
#define IDR_MENU4                               139
#define IDC_EDIT_SERVER                         1000
#define ID_BT_OK                                1000
#define IDC_EDIT1                               1001
#define ID_BT_MAKE_FILE                         1001
#define ID_BT_CANCEL                            1002
#define IDC_EDIT_ADDR                           1003
#define IDC_EDIT_LINE_PORT                      1004
#define IDC_EDIT_PORT                           1004
#define IDC_EDIT_THREAD                         1004
#define IDC_EDIT_CMD_PORT                       1005
#define IDC_EDIT_SERVER_NAME                    1005
#define IDC_COMBO1                              1006
#define IDM_MENU_MAKE_FILE                      40000
#define IDR_COMMAND12                           40000
#define IDR_COMMAND13                           40001
#define IDR_COMMAND2                            40001
#define IDR_COMMAND14                           40002
#define IDR_COMMAND3                            40002
#define IDR_COMMAND15                           40003
#define IDR_COMMAND4                            40003
#define IDR_COMMAND16                           40004
#define IDR_COMMAND5                            40004
#define IDR_COMMAND17                           40005
#define IDR_COMMAND6                            40005
#define IDR_COMMAND7                            40006
#define IDR_COMMAND8                            40007
#define IDR_COMMAND9                            40008
#define IDR_COMMAND10                           40009
#define IDR_COMMAND11                           40010
#define IDM_UP_FILE                             41001
#define IDM_DOWN_FILE                           41002
#define IDM_EXIT1                               41002
#define IDM_UP_DIRECTORY                        41003
#define IDM_DOWN_DIRECTORY                      41004
#define IDM_DELETE_FILE                         41005
#define IDM_DELETE_DIRECTORY                    41006
#define IDM_EXECFILE                            41007
#define IDM_VIEW_MAX_ICON                       41008
#define IDM_VIEW_MIN_ICON                       41009
#define IDM_VIEW_LIST                           41010
#define IDM_VIEW_X_LIST                         41011
#define IDM_FRAME_FILE                          42000
#define IDM_FRAME_CMD                           42001
#define IDM_FRAME_CAMERA                        42002
#define IDM_FRAME_SCREEN                        42003
#define IDM_FRAME_DELETE                        42004
#define IDR_COMMAND1                            42009
#define IDM_DDOS_STOP                           43000
#define IDM_DDOS_START                          43001
#define IDM_DDOS_DEL                            43002
#define IDM_DDOS_EDIT                           43003
#define IDM_DDOS_ADD                            43004
